### ISSUE TITLE
How to create the certificate?

### ISSUE THREAD

**Issue by Hussam3bd** [kawkab-oss/stcpay-node#2]
Hi there, thank you for providing this helpful SDK. 

I'm trying to implement STC Pay for my client, but I couldn't find an API document.

So my question is how to create the certificate?
I only have the Merchant API key

**Comment by elbourki** [comment]
Hey Hussam, glad to see you around! I've been following your contributions on Hsoub I/O a while ago and your work is truly inspiring :D

Concerning STC Pay, the merchant will need to get in touch with STC's support because their system works differently and is based on cert authentication, so they'll request a cert from you which you can then use to send requests to their server (we used Let's Encrypt to generate the cert).

STC Pay was a PITA to implement and that's exactly why we released this open-source package, I hope it helps!

**Comment by Hussam3bd** [comment]
Hi Abdessamad, 
Glad to hear that :D, and thank you so much for following up.

Oh, thanks for the explanation it's really saved me a lot of time, I think it's been a week trying to find the API documentation or something helpful.

We'll get in touch with the support team, hopefully we can get it done ASAP.

Thanks again for your charming work, let's keep in touch!
